// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpzebxwgwvasfxpgvwxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwemVieHdnd3Zhc2Z4cGd2d3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NjE5MDAsImV4cCI6MjA0OTMzNzkwMH0.hPJbLOcjFEs0I5dsfZFCMlWWFU_D9urYVXxON48x7r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);